### ISSUE TITLE
Double-quoted keys/values and values starting with equals are flagged as errors (red).

### ISSUE THREAD

**Issue by nicktimko** [textmate/toml.tmbundle#11]
As far as I can tell, GitHub's parser comes from here? There's an issue in it with values that start with an `=`, but only when wrapped in double quotes (`"`) and the key is *also* in double quotes.  I was fishing around for other edge-cases, but didn't come up with any

Image:

![image](https://user-images.githubusercontent.com/5297556/49662853-9884de80-fa12-11e8-8d44-847a97fd93f8.png)

Live Demo:

```toml
[ok]
'key1' = 'value'
'key2' = "value"
"key3" = 'value'
"key4" = "value"
"key4b" = """value"""

[strange]
'key1' = '=value'
'key2' = "=value"
"key3" = '=value'
"key4" = "=value"  # warning
"key4b" = """=value"""  # warning
```
